version: 2
updates:
  # Python project dependencies
  - package-ecosystem: "uv"
    directory: "/project1"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "main"
    reviewers:
      - "dependabot[bot]"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Python project dependencies
  - package-ecosystem: "uv"
    directory: "/project2"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "main"
    reviewers:
      - "dependabot[bot]"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
